# Generated by Django 5.1.1 on 2024-09-29 08:13

import api.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(validators=[api.models.DeckCard._validate_num_cards])),
                ('suit', models.CharField(choices=[('1', 'Clover'), ("(2, 'Diamond')", 'Diamond'), ("(3, 'Hearts')", 'Hearts'), ("(4, 'Spades')", 'Spades'), ("(5, 'Joker0')", 'Joker0'), ('6', 'Joker1')], max_length=15)),
                ('rank', models.CharField(choices=[('1', 'Ace'), ('2', 'Two'), ('3', 'Three'), ('4', 'Four'), ('5', 'Five'), ('6', 'Six'), ('7', 'Seven'), ('8', 'Eight'), ('9', 'Nine'), ('10', 'Ten'), ('11', 'Jack'), ('12', 'Queen'), ('13', 'King'), ('14', 'Joker')], max_length=6)),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.deck')),
            ],
            options={
                'unique_together': {('suit', 'rank', 'deck')},
            },
        ),
    ]
