# Sourced from: https://github.com/marketplace/actions/godot-ci

name: "godot-ci export"
on:
  push:
    branches:
      - main
      - master

env:
  GODOT_VERSION: 4.3
  EXPORT_NAME: caravan
  PROJECT_PATH: campaigncaravangame

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: |
          mkdir -v -p build/windows
          cd $PROJECT_PATH
          godot --import --path="." --import --headless --import --verbose --import --editor --import --quit-after 10 || echo "Exporting through the terminal with GDExtension (GDSQLite) modules installed, seems prone to segfault. But it seems it manages to generate the export anyway, so we're just gonna eat the error code"
          godot --path="." --import --headless --import --verbose --import --export-debug "Windows Desktop" ../build/windows/$EXPORT_NAME.exe || echo "Exporting through the terminal with GDExtension (GDSQLite) modules installed, seems prone to segfault. But it seems it manages to generate the export anyway, so we're just gonna eat the error code"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: build/windows

  export-linux:
    name: Linux Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: |
          mkdir -v -p build/linux
          cd $PROJECT_PATH
          godot --import --path="." --import --headless --import --verbose --import --editor --import --quit-after 10 || echo "Exporting through the terminal with GDExtension (GDSQLite) modules installed, seems prone to segfault. But it seems it manages to generate the export anyway, so we're just gonna eat the error code"
          godot --path="." --import --headless --import --verbose --import --export-debug "Linux/X11" ../build/linux/$EXPORT_NAME.x86_64 || echo "Exporting through the terminal with GDExtension (GDSQLite) modules installed, seems prone to segfault. But it seems it manages to generate the export anyway, so we're just gonna eat the error code"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux
          path: build/linux

  export-web:
    name: Web Export
    runs-on: ubuntu-20.04
    container:
      image: barichello/godot-ci:4.3
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true
      - name: Setup
        run: |
          git config --global safe.directory '*'
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Check if Git LFS is installed
        run: git lfs install
      - name: Install Python3 📚
        run: |
          apt-get update && apt-get install -y python3
      - name: Web Build
        run: |
          mkdir -v -p build/web
          cd $PROJECT_PATH
          ./disable_sqlite_extension.py
          cp SQLManager_dummy.gd.gdignore SQLManager.gd
          rm -r addons/godot-sqlite/
          godot --import --path="." --import --headless --import --verbose --import --editor --import --quit-after 10 || echo "Exporting through the terminal with GDExtension (GDSQLite) modules installed, seems prone to segfault. But it seems it manages to generate the export anyway, so we're just gonna eat the error code"
          godot --path="." --import --headless --import --verbose --import --export-debug "HTML5" ../build/web/index.html || echo "Exporting through the terminal with GDExtension (GDSQLite) modules installed, seems prone to segfault. But it seems it manages to generate the export anyway, so we're just gonna eat the error code"
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: web
          path: build/web
      - name: Install rsync 📚
        run: |
          apt-get update && apt-get install -y rsync
      - name: Deploy to GitHub Pages 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: build/web # The folder the action should deploy.

  # export-mac:
  #   name: Mac Export
  #   runs-on: ubuntu-20.04
  #   container:
  #     image: barichello/godot-ci:4.3
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #       with:
  #         lfs: true
  #     - name: Setup
  #       run: |
  #         mkdir -v -p ~/.local/share/godot/export_templates/
  #         mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
  #     - name: Mac Build
  #       run: |
  #         mkdir -v -p build/mac
  #         cd $PROJECT_PATH
  #         godot --headless --verbose --import --clean--export-debug "Mac OSX" ../build/mac/$EXPORT_NAME.zip
  #     - name: Upload Artifact
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: mac
  #         path: build/mac